import Foundation
import EVNovaKit

/// The seam between the story engine and the rest of the game.
///
/// The mission/cron runtime is deliberately self-contained: it owns control
/// bits, mission state, rewards and the galaxy clock. But some story effects
/// reach *outside* story state — spawning the ships you must destroy, playing a
/// sound, swapping the player's hull, showing briefing text. Those are declared
/// here and implemented by the systems that own them (combat/AI, audio, the
/// shipyard, the UI), which are still being built by other parts of the team.
///
/// Every method has a default no-op/log implementation (see
/// `LoggingGameServices`) so the whole story engine runs, and is fully testable,
/// **before** any of those systems exist — then each gets wired in as it lands.
public protocol GameServices: AnyObject {
    /// A mission was offered; present its briefing and accept/refuse choice.
    /// The implementer calls back into the engine's `accept`/`decline`.
    func presentMissionOffer(_ offer: MissionOffer)

    /// Show narrative text (mission completion, cron news, dialog).
    func showStoryText(_ text: String, title: String)

    /// Play a `snd ` resource (audio system).
    func playSound(id: Int)

    /// Spawn this mission's special / auxiliary ships into the current system
    /// (combat + AI system). The implementer should tag them with `missionID`
    /// so their destruction/boarding is reported back via the engine's events.
    func spawnMissionShips(missionID: Int, mission: MissionRes)

    /// Replace the player's ship (shipyard/outfit system applies the loadout).
    func changePlayerShip(to shipID: Int, mode: ChangeShipMode)

    /// The galaxy map / navigation should retarget the player to `systemID`.
    func movePlayer(toSystem systemID: Int, keepPosition: Bool)

    /// A stellar object was destroyed or regenerated by the story.
    func setStellarDestroyed(spobID: Int, destroyed: Bool)

    /// The player was forced to leave the current stellar (with optional message).
    func leaveStellar(message: String?)

    /// A reward/notification worth surfacing to the player (credits, outfit,
    /// rank changes). Purely informational; state has already been updated.
    func notify(_ event: StoryNotification)

    /// Background news from an active `crön` (Bible §`crön`, `NewsGovt`/
    /// `GovtNewsStr`/`IndNewsStr`): text to show in the news dialog while the
    /// event is active. `govt` is the government id this text is tagged for
    /// (one of the cron's up to four `NewsGovt` slots) or `nil` for the
    /// catch-all independent-news pool. Per the Bible, "local news always
    /// takes precedence over independent news" *at stations allied with a
    /// tagged government* — that precedence is a per-station rendering
    /// decision the implementer makes when the player actually looks at the
    /// news dialog (which local `govt`-tagged texts apply there, if any,
    /// else the independent one), not something the engine can resolve at
    /// cron-start time since it doesn't know which station the player will
    /// later land at.
    func showNews(text: String, govt: Int?)
}

/// A mission the engine wants to offer, with its presentation text resolved.
public struct MissionOffer: Sendable {
    public let mission: MissionRes
    /// The mission's display **name** with `<…>` wildcards expanded (e.g. the
    /// destination filled in). Use this as the dialog/list title rather than
    /// `mission.displayName`, which still holds the raw `<DST>` etc.
    public let title: String
    public let briefingText: String
    public let acceptButton: String
    public let refuseButton: String
    public let canRefuse: Bool

    public init(mission: MissionRes, title: String, briefingText: String,
                acceptButton: String, refuseButton: String, canRefuse: Bool) {
        self.mission = mission
        self.title = title
        self.briefingText = briefingText
        self.acceptButton = acceptButton
        self.refuseButton = refuseButton
        self.canRefuse = canRefuse
    }
}

/// Player-facing story notifications (for HUD toasts / logs).
public enum StoryNotification: Sendable, Equatable {
    case missionAccepted(missionID: Int, name: String)
    case missionCompleted(missionID: Int, name: String)
    case missionFailed(missionID: Int, name: String)
    case missionAborted(missionID: Int, name: String)
    case creditsChanged(delta: Int, total: Int)
    case outfitGranted(outfitID: Int)
    case outfitRemoved(outfitID: Int)
    case rankActivated(rankID: Int)
    case rankDeactivated(rankID: Int)
    case cronStarted(cronID: Int)
    case cronEnded(cronID: Int)
}

/// A ready-to-use `GameServices` that just logs. Lets the engine run headless
/// (tests, CLI, and the app before combat/audio/UI are wired up). Swap in the
/// real implementations method-by-method as they come online.
open class LoggingGameServices: GameServices {
    public var log: [String] = []
    public var lastOffer: MissionOffer?
    public init() {}

    private func record(_ s: String) { log.append(s) }

    open func presentMissionOffer(_ offer: MissionOffer) {
        lastOffer = offer
        record("offer mission #\(offer.mission.id) \"\(offer.mission.name)\"")
    }
    open func showStoryText(_ text: String, title: String) {
        record("text[\(title)]: \(text.prefix(60))")
    }
    open func playSound(id: Int) { record("sound #\(id)") }
    open func spawnMissionShips(missionID: Int, mission: MissionRes) {
        record("spawn ships for mission #\(missionID) (count \(mission.shipCount))")
    }
    open func changePlayerShip(to shipID: Int, mode: ChangeShipMode) {
        record("change ship → #\(shipID) (\(mode))")
    }
    open func movePlayer(toSystem systemID: Int, keepPosition: Bool) {
        record("move player → system #\(systemID)")
    }
    open func setStellarDestroyed(spobID: Int, destroyed: Bool) {
        record("stellar #\(spobID) destroyed=\(destroyed)")
    }
    open func leaveStellar(message: String?) {
        record("leave stellar: \(message ?? "")")
    }
    open func notify(_ event: StoryNotification) { record("notify \(event)") }
    open func showNews(text: String, govt: Int?) {
        record("news[\(govt.map(String.init) ?? "independent")]: \(text.prefix(60))")
    }
}
